/**
 * 檢索主題配置：每個主題對應 keywords（偵測/比較用）與 filenames（要查的檔案）
 * 新增產品時在此維護即可，comparison 會依 getMentionedTopics 自動決定查哪些主題
 * label: 給用戶看的名稱（例如用於「目前僅有 XXX 相關文檔」）
 */
const TOPIC_CONFIG = {
  security: {
    label: "安全與審計",
    keywords: [
      "security",
      "audit",
      "audits",
      "audited",
      "auditing",
      "bug bounty",
      "immunefi",
      "vulnerability",
      "vulnerabilities",
      "safe",
      "safety",
      "protect",
      "protection",
      "secure",
      "multi-signature",
      "multisig",
    ],
    filenames: [
      "security/audit-reports.md",
      "security/bug-bounty-immunefi.md",
      "securing-the-future-an-in-depth-look-at-lista-daos.md",
    ],
  },

  rwa: {
    label: "RWA",
    keywords: [
      "rwa",
      "real-world asset",
      "real world asset",
      "rwa market",
      "treasury",
      "treasury fund",
      "janus henderson",
      "anemoy",
      "usdt.treasury",
      "usdt.aaa",
      "實體資產",
      "真實世界資產",
      "rwa是什麼",
      "什麼是rwa",
    ],
    filenames: [
      "introduction/rwa-markets.md",
      "for-developer/rwa/README.md",
      "for-developer/rwa/smart-contract.md",
      "manual/2025-12-26_Lista-DAO-2025-Annual-Report-3e4ff3f5a085.md",
      "2025-12-26_Lista-DAO-2025-Annual-Report-3e4ff3f5a085.md",
    ],
  },

  lending: {
    label: "Lista Lending",
    keywords: [
      "lista lending",
      "lending",
      "morpho",
      "lltv",
      "liquidation loan-to-value",
      "supplier",
      "borrower",
      "vault manager",
      "interest rate model",
      "flash loan",
      "market",
      "oracle price feed",
    ],
    filenames: [
      "introduction/lista-lending/README.md",
      "lista-lending/README.md",
      "introduction/lista-lending/borrowers-and-suppliers.md",
      "introduction/lista-lending/liquidation.md",
      "introduction/lista-lending/markets.md",
      "introduction/lista-lending/user-flow.md",
      "introduction/lista-lending/oracle.md",
      "introduction/lista-lending/interest-rate-model-irm.md",
      "introduction/lista-lending/fees.md",
      "introduction/lista-lending/flash-loan.md",
      "introduction/lista-lending/vaults/README.md",
      "introduction/lista-lending/vaults/how-to-create-a-vault.md",
      "introducing-lista-lending-lista-daos-next-gen-lend.md",
      "product-guide-lista-lending.md",
      "product-update-lista-lending-vault-manager-gui.md",
      "product-update-lista-lending-alpha-zone-powering-t.md",
      "product-update-introducing-lista-daos-liquidation-.md",
      "product-update-mint-clisbnb-in-lista-lending.md",
      "Guide Running Lista's Liquidation bot.md",
      "Product Guide Borrowing USD1 on Lista Lending.md",
      "Product Guide Lista Lending.md",
      "Product Update Lista Lending Vault Manager GUI.md",
      "What makes Lista and lisUSD different.md",
    ],
  },

  cdp: {
    label: "CDP / lisUSD",
    keywords: [
      "cdp",
      "collateral debt position",
      "lisusd",
      "slisbnb",
      "bnb validator",
      "liquid staking",
      "staking",
      "mcr",
      "minimum collateral ratio",
      "dutch auction",
      "borrowing fee",
      "stability fee",
    ],
    filenames: [
      "introduction/collateral-debt-position-lisusd/README.md",
      "introduction/collateral-debt-position-lisusd/collateral/README.md",
      "introduction/collateral-debt-position-lisusd/collateral/loan-liquidation.md",
      "introduction/collateral-debt-position-lisusd/lisusd/README.md",
      "introduction/collateral-debt-position-lisusd/technical-guide.md",
      "for-developer/collateral-debt-position/README.md",
      "for-developer/collateral-debt-position/mechanics.md",
      "for-developer/collateral-debt-position/flash-loan.md",
      "for-developer/collateral-debt-position/multi-oracle.md",
      "user-guide/collateral-debt-position/README.md",
      "user-guide/collateral-debt-position/borrow-lisusd.md",
      "user-guide/collateral-debt-position/provide-collateral.md",
      "user-guide/collateral-debt-position/repay-lisusd.md",
      "user-guide/collateral-debt-position/withdraw-collateral.md",
      "introduction/liquid-staking-slisbnb/README.md",
      "introduction/liquid-staking-slisbnb/about-slisbnb.md",
      "introduction/liquid-staking-slisbnb/technical-guide.md",
      "product-update-unlocking-velista-utility-introduci.md",
      "Product Guide Looping strategies with lisUSD.md",
      "What makes Lista and lisUSD different.md",
    ],
  },

  smartLending: {
    label: "Smart Lending",
    keywords: [
      "smart lending",
      "smart-lending",
      "smartlending",
      "dex lp",
      "liquidity pool",
      "lp token",
      "impermanent loss",
      "fixed ratio",
      "custom ratio",
      "smart swap",
      "smart-swap",
    ],
    filenames: [
      "introduction/smart-lending.md",
      "introduction/smart-lending-and-swap.md",
      "user-guide/smart-lending.md",
      "ListaDAO Smart Lending A Hands-on Tutorial.md",
      "ListaDAO's Smart Lending A Hands-on Tutorial.md",
      "The Ultimate Guide to Lista Smart Swap.md",
      "Everything You Need to Know About Liquidation on Lista Smart Lending.md",
      "Product Guide LP Farming with lisUSD:USD1 on Lista DAO.md",
    ],
  },

  clisbnb: {
    label: "clisBNB",
    keywords: [
      "clisbnb",
      "slisbnbx",
      "slisbnb x",
      "pt-clisbnb",
      "yt-clisbnb",
      "pt-slisbnbx",
      "yt-slisbnbx",
      "binance launchpool",
      "launchpool",
      "megadrop",
    ],
    filenames: [
      "for-developer/clisbnb/README.md",
      "for-developer/clisbnb/smart-contract.md",
      "introduction/binance-launchpool-clisbnb/README.md",
      "introduction/binance-launchpool-clisbnb/mint-clisbnb-on-lista-lending.md",
      "introduction/binance-launchpool-clisbnb/minting-clisbnb-with-slisbnb.md",
      "user-guide/collateral-debt-position/delegating-clisbnb-to-your-binance-web3-mpc-wallet.md",
      "product-update-mint-clisbnb-in-lista-lending.md",
      "product-update-mint-clisbnb-with-bnb-slisbnb-lp-to.md",
      "Pendle Finance Lista DAO Unlocking New Yield Opportunities with clisBNB.md",
      "Product Guide delegating clisBNB.md",
      "Product Guide Earn Binance Launchpool Rewards with USD1 on Lista DAO.md",
      "Product Guide Maximizing Yield with lisUSD and pt-clisBNB.md",
      "Product Guide Participate in Binance Launchpool using slisBNB.md",
      "Product Guide Participate in Binance Launchpool using slisBNB (step-by-step).md",
    ],
  },

  velista: {
    label: "veLISTA",
    keywords: [
      "velista",
      "governance",
      "voting",
      "vote",
      "proposal",
      "snapshot",
      "lock lista",
      "locking lista",
      "unlock lista",
      "early unlock",
      "auto lock",
      "auto-lock",
      "gauge voting",
      "gauge",
      "bribe market",
      "bribe",
      "emission voting",
      "protocol fees",
      "revenue distribution",
      "rebate",
      "borrow rebate",
      "auto compound",
      "auto-compound",
    ],
    filenames: [
      "governance/lista/README.md",
      "governance/lista/lista-distribution.md",
      "governance/velista/README.md",
      "governance/velista/velista-summary.md",
      "governance/velista/lista-dao-unlocking-velista-utility.md",
      "governance/velista/velista-locking-mechanics.md",
      "governance/velista/protocol-fees.md",
      "governance/velista/revenue-cost.md",
      "governance/velista/analytics.md",
      "governance/velista/governance/README.md",
      "governance/velista/governance/governance-proposal-template.md",
      "governance/velista/velista-emissions/README.md",
      "governance/velista/velista-emissions/lp-pools.md",
      "governance/velista/gauge-voting-for-velista.md",
      "governance/velista/velista-bribe-market.md",
      "governance/velista/auto-compounding.md",
      "governance/velista/permanent-locking-of-lista-lip-016.md",
      "user-guide/lista-velista/README.md",
      "user-guide/lista-velista/lock-lista.md",
      "user-guide/lista-velista/extend-lista-lock.md",
      "user-guide/lista-velista/auto-lock.md",
      "user-guide/lista-velista/unlock-lista.md",
      "user-guide/lista-velista/claim-rewards.md",
      "user-guide/lista-velista/staking-external-lp-tokens-on-lista-dao.md",
      "user-guide/lista-velista/gauge-voting.md",
      "for-developer/lista-governance/README.md",
      "for-developer/lista-governance/smart-contract.md",
      "product-update-unlocking-velista-utility-introduci.md",
    ],
  },
};

const COMPARISON_KEYWORDS = [
  "difference",
  "differences",
  "compare",
  "comparison",
  "vs",
  "versus",
  "choose",
  "which",
  "better",
  "distinguish",
  "contrast",
  "區別",
  "差異",
  "比較",
];

module.exports = {
  TOPIC_CONFIG,
  COMPARISON_KEYWORDS,
};
